In [40]:
# Question no. 1 
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [41]:
print(list_)
print(array_list)

['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


Yes, list_ is a type of list DataType
whereas array_list is an array.

In [42]:
print(type(list_))

print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [43]:
# Question no 2
for i in list_:
    print(i, type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [44]:
# Question no 2
for i in array_list:
    print(i  , type(i))

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


In [46]:
#Question no 3

array_list = np.array(object = list_, dtype = int)

There will be change in the DataType of array_list. But there will be no change in list_.

In [11]:
for i in array_list:
    print(i  , type(i))

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [12]:
for i in list_:
    print(i, type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [20]:
print(num_array.shape)

(2, 3)


In [21]:
print(num_array.size)

6


In [34]:
new_array = np.zeros([3,3])
print(new_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
print(new_array.size)
print(new_array.shape)

9
(3, 3)


In [47]:
#Question No 5
#creating identity Matrix

array_identity = np.identity(5, dtype=int)
array_identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])